require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  Exclude:
    - config/**/*
    - db/migrate/**/*
    - 'bin/setup'
    - 'bin/update'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false