require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7.0
  TargetRailsVersion: 5.2.8

Exclude:
  - "bin/**/*"
  - "db/schema.rb"
  - "node_modules/**/*"
  - "vendor/**/*"

Style/Documentation:
  Enabled: false